### ISSUE TITLE
'make' command fails on Windows

### ISSUE THREAD

**Issue by aleks-delta** [theborderland/membership#6]
When running make on windows (GNU Make 4.3), we get the following error:
```
borderland.azurecr.io/pretix:$(git rev-parse HEAD)
"endif"
docker build --no-cache --build-arg tag=$(git rev-parse HEAD) -t borderland.azurecr.io/pretix:$(git rev-parse HEAD) .
invalid argument "borderland.azurecr.io/pretix:$(git" for "-t, --tag" flag: invalid reference format
```
This is probably due to the fact that $(git rev-parse HEAD) needs to be resolved to a git hash, and yet it stays as a string. The space after `git` cuts the string off. This occurs both in plain `cmd` and in `Powershell`. This does not happen in `Cygwin`

**Comment by darkturo** [comment]
I think you solved this, didn't you?

**Comment by aleks-delta** [comment]
Not as such without Cygwin, but perhaps it's OK to close it if Cygwin is a sufficient workaround

**Comment by darkturo** [comment]
The requirement is to have GNU Make available in your system obviously ...
How you install that, is out of the scope of the project. 

But anyway, then it means we can close this.
